# microservice-config-server 基础使用
server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:1932361772/gitconfig.git
#        encrypt:
#          enabled: true
#          username: #仓库用户名
#          password: #仓库密码

encrypt:
  key: foo  # curl -X POST http://localhost:8080/encrypt -d foobar  失败
  
profile: lnjfzi